# Generated by Django 4.2.3 on 2023-07-18 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('tile_code', models.CharField(max_length=100)),
                ('tile_size', models.CharField(max_length=100)),
                ('tile_picture', models.ImageField(upload_to='')),
                ('box_quantity_in', models.IntegerField()),
                ('box_capacity', models.IntegerField()),
                ('by_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks.person')),
            ],
        ),
    ]
