# Generated by Django 4.2.3 on 2023-07-18 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_box_capacity_alter_stock_in_box_capacity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='box_quantity_in',
            new_name='box_quantity_out',
        ),
        migrations.AlterField(
            model_name='stock',
            name='tile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock_in',
            name='tile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock_out',
            name='tile_picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
