# Generated by Django 4.2.3 on 2023-07-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_box_quantity_in_stock_box_quantity_out_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='box_quantity_out',
            new_name='box_quantity',
        ),
        migrations.RenameField(
            model_name='stock_in',
            old_name='box_quantity_in',
            new_name='box_quantity_out',
        ),
    ]
