# Generated by Django 4.2.3 on 2023-07-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_rename_box_quantity_out_stock_box_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_in',
            name='tile_picture',
            field=models.ImageField(default='', null=True, upload_to='stock/images'),
        ),
        migrations.AlterField(
            model_name='stock_out',
            name='tile_picture',
            field=models.ImageField(default='', null=True, upload_to='stock/images'),
        ),
    ]
