# Generated by Django 4.2.3 on 2023-07-18 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_alter_stock_in_tile_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock_in',
            old_name='box_quantity_out',
            new_name='box_quantity_in',
        ),
        migrations.RenameField(
            model_name='stock_out',
            old_name='box_quantity_in',
            new_name='box_quantity_out',
        ),
    ]
