# Generated by Django 4.2.3 on 2023-07-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0007_rename_box_quantity_out_stock_in_box_quantity_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='tile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='stock_in',
            name='tile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='stock/images'),
        ),
        migrations.AlterField(
            model_name='stock_out',
            name='tile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='stock/images'),
        ),
    ]
