# Generated by Django 4.2.3 on 2023-07-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_alter_stock_tile_picture_alter_stock_in_tile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_in',
            name='date_and_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock_out',
            name='date_and_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
