# Generated by Django 4.2.3 on 2023-07-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stock_in_date_and_time_stock_out_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_in',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
