# Generated by Django 4.1.3 on 2023-07-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_stock_in_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock_in',
            name='tile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='stock/images/'),
        ),
        migrations.AlterField(
            model_name='stock_out',
            name='tile_picture',
            field=models.ImageField(blank=True, default='', null=True, upload_to='stock/images/'),
        ),
    ]
